// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SmartWatch

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void homeRight(lv_event_t * e);
void appsLeft(lv_event_t * e);
void appsSettingsClicked(lv_event_t * e);
void appsFlashlightClicked(lv_event_t * e);
void updateBrightness(lv_event_t * e);
void updateVolume(lv_event_t * e);
void stepGoalCurrentlyTyping(lv_event_t * e);
void sleepTimeCurrentlyTyping(lv_event_t * e);
void updateSettings(lv_event_t * e);
void flashlightPressed(lv_event_t * e);
void settingsRight(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
